name: Package Application with Pyinstaller

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: src

    - uses: actions/upload-artifact@v2
      with:
        name: excel_splitter
        path: src/dist
        
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files:
         excel_splitter.zip
      env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
