# This is a basic workflow to help you get started with Actions

name: pylint3

on: [push]

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: A job to run github action
    steps:
    - name: Run Action Step
      id: hello
      uses: LakshitF/pylint3-action@master
      with:
        filename: 'src/excel_splitter.py'
